### PR TITLE
build(docker): initial Dockerfile and docker-compose.yml

### PR DESCRIPTION
**Pull request by Gabrielfernandes7**
#19 Issue Docker

### CODE REVIEW

**Comment by Gabrielfernandes7** [comment]
@microsoft-github-policy-service agree

**Comment by Deng-Xian-Sheng** [comment]
ollama?

**Comment by Gabrielfernandes7** [comment]
> ollama?

Hello friend. I do not get it. Are u asking about model or repository profile ollama?

I am newcomer to the open-source community

**Comment by Loksly** [comment]
https://ollama.com/

**Comment by Gabrielfernandes7** [comment]
> https://ollama.com/

No, I used the Llama3 model from Hugging Face, the same one described in the documentation. Ollama is a repository with various models, but I'm not using any from there. Inclusively.

**Comment by JoseCarlosGarcia95** [comment]
GJ! I think should be nice to pass model as build-arg to make image more flexible :)

**Review by JoseCarlosGarcia95 — APPROVED** [review]

**Comment by Loksly** [comment]
Hi, 
it might not be your fault but I get some errors trying to build the docker image.

This is the error log:

```
[...]
84.47 Stack dump:
84.47 0.	Program arguments: /usr/bin/clang++ -DGGML_BITNET_X86_TL2 -DLLAMA_BUILD -DLLAMA_SHARED -Dllama_EXPORTS -I/BitNet/3rdparty/llama.cpp/src/. -I/BitNet/3rdparty/llama.cpp/src/../include -I/BitNet/3rdparty/llama.cpp/ggml/src/../include -I/BitNet/3rdparty/llama.cpp/ggml/src/../../../../include -O3 -DNDEBUG -fPIC -MD -MT 3rdparty/llama.cpp/src/CMakeFiles/llama.dir/llama.cpp.o -MF CMakeFiles/llama.dir/llama.cpp.o.d -o CMakeFiles/llama.dir/llama.cpp.o -c /BitNet/3rdparty/llama.cpp/src/llama.cpp
84.47 1.	<eof> parser at end of file
84.47 2.	Code generation
84.47 3.	Running pass 'Function Pass Manager' on module '/BitNet/3rdparty/llama.cpp/src/llama.cpp'.
84.47 4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@_ZL16llm_load_tensorsR18llama_model_loaderR11llama_modeli16llama_split_modeiPKfbPFbfPvES6_'
84.47 clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
84.47 Alpine clang version 17.0.6
84.47 Target: x86_64-alpine-linux-musl
84.47 Thread model: posix
84.47 InstalledDir: /usr/bin
84.47 Configuration file: /etc/clang17/x86_64-alpine-linux-musl.cfg
84.66 clang++: note: diagnostic msg: 
84.66 ********************
84.66 
84.66 PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
84.66 Preprocessed source(s) and associated run script(s) are located at:
84.66 clang++: note: diagnostic msg: /tmp/llama-f6223b.cpp
84.66 clang++: note: diagnostic msg: /tmp/llama-f6223b.sh
84.66 clang++: note: diagnostic msg: 
84.66 
84.66 ********************
84.69 gmake[3]: *** [3rdparty/llama.cpp/src/CMakeFiles/llama.dir/build.make:76: 3rdparty/llama.cpp/src/CMakeFiles/llama.dir/llama.cpp.o] Error 1
84.69 gmake[2]: *** [CMakeFiles/Makefile2:785: 3rdparty/llama.cpp/src/CMakeFiles/llama.dir/all] Error 2
84.69 gmake[1]: *** [CMakeFiles/Makefile2:1700: 3rdparty/llama.cpp/examples/main/CMakeFiles/llama-cli.dir/rule] Error 2
84.69 gmake: *** [Makefile:598: llama-cli] Error 2
------
Dockerfile:14
--------------------
  13 |     
  14 | >>> RUN cmake -B build -DBITNET_X86_TL2=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ && \
  15 | >>>     cmake --build build --target llama-cli --config Release
  16 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cmake -B build -DBITNET_X86_TL2=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ &&     cmake --build build --target llama-cli --config Release" did not complete successfully: exit code: 2
```

How to reproduce:

```bash
git clone git@github.com:Gabrielfernandes7/BitNet.git
cd BitNet/
docker build .
```

**Comment by Gabrielfernandes7** [comment]
> Hi, it might not be your fault but I get some errors trying to build the docker image.
> 
> This is the error log:
> 
> ```
> [...]
> 84.47 Stack dump:
> 84.47 0.	Program arguments: /usr/bin/clang++ -DGGML_BITNET_X86_TL2 -DLLAMA_BUILD -DLLAMA_SHARED -Dllama_EXPORTS -I/BitNet/3rdparty/llama.cpp/src/. -I/BitNet/3rdparty/llama.cpp/src/../include -I/BitNet/3rdparty/llama.cpp/ggml/src/../include -I/BitNet/3rdparty/llama.cpp/ggml/src/../../../../include -O3 -DNDEBUG -fPIC -MD -MT 3rdparty/llama.cpp/src/CMakeFiles/llama.dir/llama.cpp.o -MF CMakeFiles/llama.dir/llama.cpp.o.d -o CMakeFiles/llama.dir/llama.cpp.o -c /BitNet/3rdparty/llama.cpp/src/llama.cpp
> 84.47 1.	<eof> parser at end of file
> 84.47 2.	Code generation
> 84.47 3.	Running pass 'Function Pass Manager' on module '/BitNet/3rdparty/llama.cpp/src/llama.cpp'.
> 84.47 4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@_ZL16llm_load_tensorsR18llama_model_loaderR11llama_modeli16llama_split_modeiPKfbPFbfPvES6_'
> 84.47 clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
> 84.47 Alpine clang version 17.0.6
> 84.47 Target: x86_64-alpine-linux-musl
> 84.47 Thread model: posix
> 84.47 InstalledDir: /usr/bin
> 84.47 Configuration file: /etc/clang17/x86_64-alpine-linux-musl.cfg
> 84.66 clang++: note: diagnostic msg: 
> 84.66 ********************
> 84.66 
> 84.66 PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
> 84.66 Preprocessed source(s) and associated run script(s) are located at:
> 84.66 clang++: note: diagnostic msg: /tmp/llama-f6223b.cpp
> 84.66 clang++: note: diagnostic msg: /tmp/llama-f6223b.sh
> 84.66 clang++: note: diagnostic msg: 
> 84.66 
> 84.66 ********************
> 84.69 gmake[3]: *** [3rdparty/llama.cpp/src/CMakeFiles/llama.dir/build.make:76: 3rdparty/llama.cpp/src/CMakeFiles/llama.dir/llama.cpp.o] Error 1
> 84.69 gmake[2]: *** [CMakeFiles/Makefile2:785: 3rdparty/llama.cpp/src/CMakeFiles/llama.dir/all] Error 2
> 84.69 gmake[1]: *** [CMakeFiles/Makefile2:1700: 3rdparty/llama.cpp/examples/main/CMakeFiles/llama-cli.dir/rule] Error 2
> 84.69 gmake: *** [Makefile:598: llama-cli] Error 2
> ------
> Dockerfile:14
> --------------------
>   13 |     
>   14 | >>> RUN cmake -B build -DBITNET_X86_TL2=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ && \
>   15 | >>>     cmake --build build --target llama-cli --config Release
>   16 |     
> --------------------
> ERROR: failed to solve: process "/bin/sh -c cmake -B build -DBITNET_X86_TL2=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ &&     cmake --build build --target llama-cli --config Release" did not complete successfully: exit code: 2
> ```
> 
> How to reproduce:
> 
> ```shell
> git clone git@github.com:Gabrielfernandes7/BitNet.git
> cd BitNet/
> docker build .
> ```

you can use command ```docker compose up --build```

**Pull request closed without merging**
